/** Tradução dos nomes das seleções (a API retorna em inglês). */
const TEAM_NAMES_PT: Record<string, string> = {
  Brazil: "Brasil",
  Germany: "Alemanha",
  France: "França",
  Spain: "Espanha",
  England: "Inglaterra",
  Netherlands: "Holanda",
  Belgium: "Bélgica",
  Croatia: "Croácia",
  Italy: "Itália",
  Portugal: "Portugal",
  Switzerland: "Suíça",
  Denmark: "Dinamarca",
  Norway: "Noruega",
  Sweden: "Suécia",
  Poland: "Polônia",
  Austria: "Áustria",
  Scotland: "Escócia",
  Wales: "País de Gales",
  Ireland: "Irlanda",
  Turkey: "Turquia",
  Ukraine: "Ucrânia",
  Serbia: "Sérvia",
  Slovenia: "Eslovênia",
  Slovakia: "Eslováquia",
  "Czech Republic": "Tchéquia",
  Czechia: "Tchéquia",
  Hungary: "Hungria",
  Romania: "Romênia",
  Greece: "Grécia",
  Albania: "Albânia",
  Georgia: "Geórgia",
  Argentina: "Argentina",
  Uruguay: "Uruguai",
  Colombia: "Colômbia",
  Ecuador: "Equador",
  Paraguay: "Paraguai",
  Bolivia: "Bolívia",
  Peru: "Peru",
  Chile: "Chile",
  Venezuela: "Venezuela",
  "United States": "Estados Unidos",
  USA: "Estados Unidos",
  Mexico: "México",
  Canada: "Canadá",
  Panama: "Panamá",
  "Costa Rica": "Costa Rica",
  Honduras: "Honduras",
  Jamaica: "Jamaica",
  Haiti: "Haiti",
  Curacao: "Curaçao",
  Curaçao: "Curaçao",
  Japan: "Japão",
  "South Korea": "Coreia do Sul",
  "Korea Republic": "Coreia do Sul",
  Australia: "Austrália",
  "Saudi Arabia": "Arábia Saudita",
  Iran: "Irã",
  Qatar: "Catar",
  Uzbekistan: "Uzbequistão",
  Jordan: "Jordânia",
  Iraq: "Iraque",
  "United Arab Emirates": "Emirados Árabes",
  Indonesia: "Indonésia",
  Morocco: "Marrocos",
  Senegal: "Senegal",
  Tunisia: "Tunísia",
  Algeria: "Argélia",
  Egypt: "Egito",
  Nigeria: "Nigéria",
  Ghana: "Gana",
  Cameroon: "Camarões",
  "Ivory Coast": "Costa do Marfim",
  "Côte d'Ivoire": "Costa do Marfim",
  "South Africa": "África do Sul",
  "Cape Verde": "Cabo Verde",
  "Cape Verde Islands": "Cabo Verde",
  "New Zealand": "Nova Zelândia",
};

export function teamNamePt(name: string | null): string {
  if (!name) return "A definir";
  const clean = name.replace(/ \((W|U\d+)\)$/, "");
  return TEAM_NAMES_PT[clean] ?? clean;
}
